### ISSUE TITLE
Unexpected exception after re-adding integration

### ISSUE THREAD

**Issue by galex80** [adamkrol93/wolf-smartset#1]
When i've recognized, that for this integration, all entities become unavailable, first i've tried to restart home assistant. Since a restart didn't reactivate these entities, i've tried to delete and re-added the integration again. When i try to login, i get the error "unexpected error". The log is as followed:
`Logger: homeassistant.components.wolflink.config_flow
Source: components/wolflink/config_flow.py:46
Integration: Wolf SmartSet Service (documentation, issues)
First occurred: 8:23:32 AM (2 occurrences)
Last logged: 8:24:19 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/wolflink/config_flow.py", line 46, in async_step_user
    self.fetched_systems = await wolf_client.fetch_system_list()
  File "/usr/local/lib/python3.8/site-packages/wolf_smartset/wolf_client.py", line 75, in fetch_system_list
    system_list = await self.__request('get', 'api/portal/GetSystemList')
  File "/usr/local/lib/python3.8/site-packages/wolf_smartset/wolf_client.py", line 35, in __request
    await self.__authorize()
  File "/usr/local/lib/python3.8/site-packages/wolf_smartset/wolf_client.py", line 66, in __authorize
    await self.__authorize_and_session()
  File "/usr/local/lib/python3.8/site-packages/wolf_smartset/wolf_client.py", line 70, in __authorize_and_session
    self.tokens = await self.token_auth.token(session)
  File "/usr/local/lib/python3.8/site-packages/wolf_smartset/token_auth.py", line 36, in token
    json = resp.json()
  File "/usr/local/lib/python3.8/site-packages/httpx/_models.py", line 1116, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Any help would be appreciate.

**Comment by adamkrol93** [comment]
It was a temporary problem with Wolf service. It works now at lease for me.

**Comment by galex80** [comment]
Since this was a temporary issue, as @adamkrol93 mentioned, I've closed this issue.
