### ISSUE TITLE
i can not get any sensor anymore since 2021.9

### ISSUE THREAD

**Issue by ollimagic** [adamkrol93/wolf-smartset#7]
Logger: homeassistant.config_entries
Source: components/wolflink/__init__.py:129
First occurred: 8:59:14 (1 occurrences)
Last logged: 8:59:14

Error setting up entry Hauptheizung for wolflink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/wolflink/__init__.py", line 46, in async_setup_entry
    parameters = await fetch_parameters_init(wolf_client, gateway_id, device_id)
  File "/usr/src/homeassistant/homeassistant/components/wolflink/__init__.py", line 136, in fetch_parameters_init
    return await fetch_parameters(client, gateway_id, device_id)
  File "/usr/src/homeassistant/homeassistant/components/wolflink/__init__.py", line 129, in fetch_parameters
    fetched_parameters = await client.fetch_parameters(gateway_id, device_id)
  File "/usr/local/lib/python3.9/site-packages/wolf_smartset/wolf_client.py", line 97, in fetch_parameters
    tab_views = desc[MENU_ITEMS][0][TAB_VIEWS]
KeyError: 'MenuItems'

**Comment by galex80** [comment]
I'm getting the same error message. 
I've already tried to set up this integration from scratch again, but without any success 🙁

**Comment by ollimagic** [comment]
i have a question will you fix it or is these intigration never working again?

**Comment by adamkrol93** [comment]
Till the end of September I will not have time to dive into it. But I hope I will be able to fix this integration.

**Comment by ollimagic** [comment]
Ok super thank you
Regards
Oliver

Adam Król ***@***.***> schrieb am Mi., 15. Sept. 2021, 10:41:
